### ISSUE TITLE
Improve outline configuration

### ISSUE THREAD

**Issue by uliska** [uliska/mkdocs-library#1]
I think the reading of the project outline can be improved by assuming that a *first* book with the name `main` *is* the main book. There will never be the need for a custom name, especially since this particular name will *not* be used as a path segment.

We use `oyaml` so we have ordered dictionaries, so I suggest the following syntax for the `outline.yml` file:

```yaml
main:
  title: "The great book"
intro:
  title: "Introduction"
api:
  title: "API documentation"
```

This will result in a site *with* main book and two subbooks with the path segments `intro` and `api`
